Sprint 1/issue 6/delete events option
BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos pull request #14
Opened 2024-01-30 23:30 UTC by AnaCarrizales

"Eliminar evento" button was created as well as event partial

![Screenshot from 2024-01-30 17-30-07](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/54050167/9b38e41c-2ebd-4571-b4eb-5d592f974302)
![Screenshot from 2024-01-30 17-30-21](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/54050167/ec11f2ba-f759-439d-9b48-db1d8b444cf3)

2024-01-30 23:55 UTC, MauricioNC requested changes

2024-01-30 23:55 UTC, MauricioNC commented on app/controllers/events_controller.rb
> +    @evento_partial = 'event'
Delete this line as we discuss

2024-01-30 23:55 UTC, MauricioNC commented on app/controllers/events_controller.rb
> +    @evento_partial = 'event'
Delete this line too

2024-01-30 23:57 UTC, MauricioNC approved these changes
LGTM!

2024-01-31 00:05 UTC, juperameza approved these changes
LGTM

2024-01-31 00:07 UTC, merged