Sprint 2/issue 1/login
BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos pull request #23
Opened 2024-02-01 00:52 UTC by AnaCarrizales

"Iniciar sesión" function was created using Devise tool

![Screenshot from 2024-01-31 18-51-48](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/54050167/f008e678-6aff-4dba-93f7-b6462184af11)

2024-02-01 01:09 UTC, MauricioNC requested changes

2024-02-01 01:09 UTC, MauricioNC commented on app/views/events/index.html.erb
> +<% end %>
Add an empty line at the end of your code

2024-02-01 01:10 UTC, MauricioNC commented
Please delete all files you don't need

2024-02-01 01:30 UTC, MauricioNC approved these changes

2024-02-02 00:26 UTC, juperameza approved these changes

2024-02-02 00:27 UTC, merged