Log in and users registration
BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos pull request #24
Opened 2024-02-03 00:49 UTC by ramondiaz21

User registration features were created.

- Views, controllers, models and databases were created so that users can register in the platform.
- We also restricted access to events to users who did not have an account.

![Screenshot_12](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/26145239/acb9b247-15e4-4f85-9a89-2f8667c3ae25)
![Screenshot_13](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/26145239/e694d851-cddd-42b4-b261-0558b23f1570)
![Screenshot_14](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/26145239/ac42305e-c54a-46cc-9b51-4231379b3b19)
![Screenshot_15](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/26145239/e7b7c865-c65a-4187-b899-9d2ea0a5be23)

2024-02-03 00:59 UTC, juperameza requested changes
just that
Kudos on using l8n

2024-02-03 00:59 UTC, juperameza commented on app/views/layouts/application.html.erb
> +</html>
add a new line at the end of this file

2024-02-03 01:14 UTC, MauricioNC approved these changes

2024-02-04 18:32 UTC, juperameza approved these changes
Lgtm

2024-02-06 23:34 UTC, merged