Sprint 3/issue 1/email verification
BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos pull request #28
Opened 2024-02-17 01:18 UTC by AnaCarrizales

Implemented Verify email tool

![Screenshot from 2024-02-16 19-17-34](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/54050167/a01d26d9-c5b0-4239-8859-348e58091c8e)
![Screenshot from 2024-02-16 19-18-02](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/54050167/6dfb94cf-935f-4067-97b5-dab74e4a6f05)

2024-02-17 01:26 UTC, MauricioNC requested changes

2024-02-17 01:26 UTC, MauricioNC commented on app/mailers/user_mailer.rb
> +    pp params
Don't let test lines

2024-02-17 21:11 UTC, juperameza requested changes
attend @MauricioNC comment

2024-02-17 21:11 UTC, juperameza commented on test/mailers/user_mailer_test.rb
> +  # end
Remove this unused code

2024-02-19 23:16 UTC, juperameza approved these changes

2024-02-19 23:16 UTC, MauricioNC approved these changes

2024-02-19 23:17 UTC, merged