Sprint 3/issue 4/csv
BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos pull request #32
Opened 2024-02-23 01:09 UTC by AnaCarrizales

Added export list of events depending on the type of event tool

![Screenshot from 2024-02-22 19-08-33](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/54050167/6f01fa1b-9199-470b-8cdb-29169dcacee6)
![Screenshot from 2024-02-22 19-08-53](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/54050167/938c5a06-126f-47fa-b97f-d6e34da762c2)

2024-02-23 01:22 UTC, MauricioNC requested changes

2024-02-23 01:22 UTC, MauricioNC commented on app/controllers/events_controller.rb
> +    puts(eventos)
Remove debugging code

2024-02-23 02:24 UTC, juperameza requested changes
attend @MauricioNC  comment

2024-02-23 18:58 UTC, nlinedev approved these changes

2024-02-23 18:58 UTC, MauricioNC approved these changes

2024-02-24 00:20 UTC, juperameza approved these changes

2024-03-06 23:37 UTC, merged