Create home screen
BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos pull request #8
Opened 2024-01-24 23:42 UTC by AnaCarrizales

Quick Info

**What does this change?**
Home screen is made up.
**Why are you changing that?**
To have a friendly view.
![Screenshot from 2024-01-24 17-30-25](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-02-s5a1-administrador-de-eventos/assets/54050167/83a84f7e-531a-4816-a65a-a77323ab8c75)

2024-01-24 23:52 UTC, MauricioNC commented on app/assets/stylesheets/application.css
> +}
if you are not applying any styles to the body, please remove it from the CSS

2024-01-24 23:58 UTC, MauricioNC commented on app/controllers/planeadores_de_eventos_controller.rb
> +end
In a PR you should commit only little changes, keep this in mind and the next time only commit the affected files.

For example, for this PR, the home controller with the index method, the CSS styles and the index view for the Home controller it's ok.

2024-01-25 00:03 UTC, MauricioNC commented on app/views/home/index.html.erb
> +</section>
Please indent this code

2024-01-25 00:06 UTC, MauricioNC commented on config/routes.rb
>    # Defines the root path route ("/")
Remove unnecessary comments

2024-01-25 00:12 UTC, MauricioNC commented on app/assets/stylesheets/application.css
> +
It's preferable to create separated files for the styles, e.g. one CSS file for home styles, one CSS file for navbar, one CSS file for the footer, etc. By this way, you have all the styles well organized and separated from each other.

In your application.css file you can only add styles to reset the  predefined styles by the browser.

2024-01-25 00:14 UTC, juperameza requested changes

2024-01-25 00:14 UTC, juperameza commented on app/assets/stylesheets/application.css
> + .home {
Apart from mauricio comment sort properties alphabetically

2024-01-25 00:14 UTC, juperameza commented on app/controllers/planeadores_de_eventos_controller.rb
> +class PlaneadoresDeEventosController < ApplicationController
Youre using scaffold can you explain fully what the command does?

2024-01-25 00:14 UTC, juperameza commented on app/views/layouts/application.html.erb
> +    </nav>
Why is this here and in the other pr??

2024-01-25 00:15 UTC, MauricioNC commented on app/views/layouts/application.html.erb
> +    </nav>
you can export this nav within a partial, and just render it instead of have all the code in the application.html.erb

2024-01-25 00:27 UTC, MauricioNC requested changes
Add a new line a the end of the code

2024-01-25 00:36 UTC, MauricioNC commented on app/views/home/index.html.erb
> +</section>
```suggestion
</section>

```
Add a new line at the end of the code

2024-01-25 00:40 UTC, MauricioNC commented on app/views/home/index.html.erb
> +</section>
Also add an empty line at the end of the code

2024-01-25 01:08 UTC, juperameza approved these changes

2024-01-25 23:13 UTC, merged